const db = require('./db');

const listings = [
  {
    title: 'Sun-Filled Corner Two-Bedroom',
    neighborhood: 'Astoria',
    address: '31-15 30th Ave, Astoria, NY 11102',
    listing_type: 'rent',
    property_type: 'Condo',
    price: 3200,
    beds: 2,
    baths: 1,
    sqft: 950,
    description: 'Bright corner unit two blocks from the N/W train, with south and east exposures, an updated kitchen with stainless appliances, and a shared roof deck with Manhattan skyline views.',
    image_seed: 'astoria-1',
    lat: 40.7644, lng: -73.9235,
    featured: 1,
  },
  {
    title: 'Renovated Row House with Backyard',
    neighborhood: 'Ridgewood',
    address: '60-22 Fresh Pond Rd, Ridgewood, NY 11385',
    listing_type: 'sale',
    property_type: 'Multi-Family',
    price: 899000,
    beds: 4,
    baths: 2,
    sqft: 1800,
    description: 'Classic Ridgewood row house fully renovated top to bottom. Two-family layout, finished basement, private backyard, and detached garage. Close to the M train and Fresh Pond Road shopping strip.',
    image_seed: 'ridgewood-1',
    lat: 40.7043, lng: -73.9105,
    featured: 1,
  },
  {
    title: 'Luxury High-Rise One-Bedroom',
    neighborhood: 'Long Island City',
    address: '13-01 Jackson Ave, Long Island City, NY 11101',
    listing_type: 'rent',
    property_type: 'Condo',
    price: 3650,
    beds: 1,
    baths: 1,
    sqft: 700,
    description: 'Full-service high-rise with 24-hour doorman, gym, and rooftop lounge. Floor-to-ceiling windows facing the Manhattan skyline, in-unit washer/dryer, steps from the 7/E/M/G trains.',
    image_seed: 'lic-1',
    lat: 40.7447, lng: -73.9485,
    featured: 1,
  },
  {
    title: 'Colonial with Detached Garage',
    neighborhood: 'Bayside',
    address: '212-09 26th Ave, Bayside, NY 11360',
    listing_type: 'sale',
    property_type: 'Single-Family',
    price: 1150000,
    beds: 4,
    baths: 3,
    sqft: 2400,
    description: 'Traditional brick colonial on a quiet tree-lined street. Updated eat-in kitchen, hardwood floors throughout, finished basement with separate entrance, and a two-car detached garage.',
    image_seed: 'bayside-1',
    lat: 40.7684, lng: -73.7734,
    featured: 0,
  },
  {
    title: 'Prewar Junior Four',
    neighborhood: 'Jackson Heights',
    address: '34-56 82nd St, Jackson Heights, NY 11372',
    listing_type: 'sale',
    property_type: 'Co-op',
    price: 385000,
    beds: 2,
    baths: 1,
    sqft: 1050,
    description: 'Classic prewar co-op with high ceilings, original crown moldings, and a windowed kitchen. Located in the Jackson Heights Historic District, close to the 7 train and Travers Park.',
    image_seed: 'jh-1',
    lat: 40.7527, lng: -73.8827,
    featured: 0,
  },
  {
    title: 'Modern Studio Near the Park',
    neighborhood: 'Forest Hills',
    address: '108-20 71st Rd, Forest Hills, NY 11375',
    listing_type: 'rent',
    property_type: 'Condo',
    price: 2150,
    beds: 0,
    baths: 1,
    sqft: 520,
    description: 'Efficient studio layout with a separate sleeping alcove, renovated bathroom, and large windows. Two blocks from Forest Park and the E/F/M/R trains at 71st-Continental Ave.',
    image_seed: 'fh-1',
    lat: 40.7215, lng: -73.8448,
    featured: 0,
  },
  {
    title: 'Family Home Near Flushing Meadows',
    neighborhood: 'Flushing',
    address: '141-27 Northern Blvd, Flushing, NY 11354',
    listing_type: 'sale',
    property_type: 'Single-Family',
    price: 1050000,
    beds: 5,
    baths: 3,
    sqft: 2600,
    description: 'Spacious single-family home with an open floor plan, updated kitchen, and finished walk-out basement. Minutes from Flushing Meadows Corona Park and the 7 train terminus at Main Street.',
    image_seed: 'flushing-1',
    lat: 40.7654, lng: -73.8318,
    featured: 1,
  },
  {
    title: 'Cozy One-Bedroom Above Retail',
    neighborhood: 'Sunnyside',
    address: '43-25 Skillman Ave, Sunnyside, NY 11104',
    listing_type: 'rent',
    property_type: 'Apartment',
    price: 2400,
    beds: 1,
    baths: 1,
    sqft: 600,
    description: 'Charming one-bedroom above a quiet retail strip, hardwood floors, updated kitchen with dishwasher. Short walk to Sunnyside Gardens and the 7 train at 46th Street.',
    image_seed: 'sunnyside-1',
    lat: 40.7433, lng: -73.9196,
    featured: 0,
  },
  {
    title: 'Turnkey Two-Family Investment',
    neighborhood: 'Elmhurst',
    address: '82-10 Broadway, Elmhurst, NY 11373',
    listing_type: 'sale',
    property_type: 'Multi-Family',
    price: 949000,
    beds: 6,
    baths: 4,
    sqft: 2200,
    description: 'Well-maintained two-family with separate meters, finished basement, and a shared driveway. Strong rental history and close proximity to the 7/M/R trains and Queens Center Mall.',
    image_seed: 'elmhurst-1',
    lat: 40.7362, lng: -73.8783,
    featured: 0,
  },
  {
    title: 'Garden Apartment with Private Patio',
    neighborhood: 'Rego Park',
    address: '63-08 99th St, Rego Park, NY 11374',
    listing_type: 'rent',
    property_type: 'Apartment',
    price: 2600,
    beds: 2,
    baths: 1,
    sqft: 850,
    description: 'Ground-floor garden apartment with a private patio, updated kitchen and bath, and in-building laundry. Near Rego Center and the M/R trains at 63rd Drive.',
    image_seed: 'regopark-1',
    lat: 40.7259, lng: -73.8613,
    featured: 0,
  },
  {
    title: 'Contemporary Townhouse',
    neighborhood: 'Douglaston',
    address: '243-15 Northern Blvd, Douglaston, NY 11362',
    listing_type: 'sale',
    property_type: 'Townhouse',
    price: 1295000,
    beds: 4,
    baths: 3,
    sqft: 2800,
    description: 'Contemporary townhouse with an attached garage, open-concept living/dining, and a private backyard. Located near Douglaston Manor and the LIRR station for a quick Manhattan commute.',
    image_seed: 'douglaston-1',
    lat: 40.7688, lng: -73.7432,
    featured: 0,
  },
  {
    title: 'Loft-Style Rental in Arts District',
    neighborhood: 'Long Island City',
    address: '22-45 Jackson Ave, Long Island City, NY 11101',
    listing_type: 'rent',
    property_type: 'Loft',
    price: 4100,
    beds: 2,
    baths: 2,
    sqft: 1200,
    description: 'Industrial-chic loft with exposed brick, 11-foot ceilings, and oversized windows. In the heart of the LIC arts district, near MoMA PS1 and multiple subway lines.',
    image_seed: 'lic-2',
    lat: 40.7462, lng: -73.9425,
    featured: 0,
  },
];

const insert = db.prepare(`
  INSERT INTO listings
    (title, neighborhood, address, listing_type, property_type, price, beds, baths, sqft, description, image_seed, lat, lng, featured)
  VALUES
    (@title, @neighborhood, @address, @listing_type, @property_type, @price, @beds, @baths, @sqft, @description, @image_seed, @lat, @lng, @featured)
`);

const count = db.prepare('SELECT COUNT(*) AS c FROM listings').get().c;

if (count === 0) {
  const insertMany = db.transaction((rows) => {
    for (const row of rows) insert.run(row);
  });
  insertMany(listings);
  console.log(`Seeded ${listings.length} listings.`);
} else {
  console.log(`Listings table already has ${count} rows — skipping seed.`);
}
